version: "3.9"

services:
  index:
    build:
      context: .
      dockerfile: Dockerfile
      image: index:latest

    container_name: index
    ports:
      - "5000:5000"
    restart: unless-stopped
