version: "3.9"

services:
  index:
    build:
      context: .
      dockerfile: Dockerfile
    image: index:latest

    container_name: index
    ports:
      - "5001:5001"
    restart: unless-stopped
